require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DemandsitesController do

  # This should return the minimal set of attributes required to create a valid
  # Demandsite. As you add validations to Demandsite, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DemandsitesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all demandsites as @demandsites" do
      demandsite = Demandsite.create! valid_attributes
      get :index, {}, valid_session
      assigns(:demandsites).should eq([demandsite])
    end
  end

  describe "GET show" do
    it "assigns the requested demandsite as @demandsite" do
      demandsite = Demandsite.create! valid_attributes
      get :show, {:id => demandsite.to_param}, valid_session
      assigns(:demandsite).should eq(demandsite)
    end
  end

  describe "GET new" do
    it "assigns a new demandsite as @demandsite" do
      get :new, {}, valid_session
      assigns(:demandsite).should be_a_new(Demandsite)
    end
  end

  describe "GET edit" do
    it "assigns the requested demandsite as @demandsite" do
      demandsite = Demandsite.create! valid_attributes
      get :edit, {:id => demandsite.to_param}, valid_session
      assigns(:demandsite).should eq(demandsite)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Demandsite" do
        expect {
          post :create, {:demandsite => valid_attributes}, valid_session
        }.to change(Demandsite, :count).by(1)
      end

      it "assigns a newly created demandsite as @demandsite" do
        post :create, {:demandsite => valid_attributes}, valid_session
        assigns(:demandsite).should be_a(Demandsite)
        assigns(:demandsite).should be_persisted
      end

      it "redirects to the created demandsite" do
        post :create, {:demandsite => valid_attributes}, valid_session
        response.should redirect_to(Demandsite.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved demandsite as @demandsite" do
        # Trigger the behavior that occurs when invalid params are submitted
        Demandsite.any_instance.stub(:save).and_return(false)
        post :create, {:demandsite => {}}, valid_session
        assigns(:demandsite).should be_a_new(Demandsite)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Demandsite.any_instance.stub(:save).and_return(false)
        post :create, {:demandsite => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested demandsite" do
        demandsite = Demandsite.create! valid_attributes
        # Assuming there are no other demandsites in the database, this
        # specifies that the Demandsite created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Demandsite.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => demandsite.to_param, :demandsite => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested demandsite as @demandsite" do
        demandsite = Demandsite.create! valid_attributes
        put :update, {:id => demandsite.to_param, :demandsite => valid_attributes}, valid_session
        assigns(:demandsite).should eq(demandsite)
      end

      it "redirects to the demandsite" do
        demandsite = Demandsite.create! valid_attributes
        put :update, {:id => demandsite.to_param, :demandsite => valid_attributes}, valid_session
        response.should redirect_to(demandsite)
      end
    end

    describe "with invalid params" do
      it "assigns the demandsite as @demandsite" do
        demandsite = Demandsite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Demandsite.any_instance.stub(:save).and_return(false)
        put :update, {:id => demandsite.to_param, :demandsite => {}}, valid_session
        assigns(:demandsite).should eq(demandsite)
      end

      it "re-renders the 'edit' template" do
        demandsite = Demandsite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Demandsite.any_instance.stub(:save).and_return(false)
        put :update, {:id => demandsite.to_param, :demandsite => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested demandsite" do
      demandsite = Demandsite.create! valid_attributes
      expect {
        delete :destroy, {:id => demandsite.to_param}, valid_session
      }.to change(Demandsite, :count).by(-1)
    end

    it "redirects to the demandsites list" do
      demandsite = Demandsite.create! valid_attributes
      delete :destroy, {:id => demandsite.to_param}, valid_session
      response.should redirect_to(demandsites_url)
    end
  end

end
