require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SupplysitesController do

  # This should return the minimal set of attributes required to create a valid
  # Supplysite. As you add validations to Supplysite, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SupplysitesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all supplysites as @supplysites" do
      supplysite = Supplysite.create! valid_attributes
      get :index, {}, valid_session
      assigns(:supplysites).should eq([supplysite])
    end
  end

  describe "GET show" do
    it "assigns the requested supplysite as @supplysite" do
      supplysite = Supplysite.create! valid_attributes
      get :show, {:id => supplysite.to_param}, valid_session
      assigns(:supplysite).should eq(supplysite)
    end
  end

  describe "GET new" do
    it "assigns a new supplysite as @supplysite" do
      get :new, {}, valid_session
      assigns(:supplysite).should be_a_new(Supplysite)
    end
  end

  describe "GET edit" do
    it "assigns the requested supplysite as @supplysite" do
      supplysite = Supplysite.create! valid_attributes
      get :edit, {:id => supplysite.to_param}, valid_session
      assigns(:supplysite).should eq(supplysite)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Supplysite" do
        expect {
          post :create, {:supplysite => valid_attributes}, valid_session
        }.to change(Supplysite, :count).by(1)
      end

      it "assigns a newly created supplysite as @supplysite" do
        post :create, {:supplysite => valid_attributes}, valid_session
        assigns(:supplysite).should be_a(Supplysite)
        assigns(:supplysite).should be_persisted
      end

      it "redirects to the created supplysite" do
        post :create, {:supplysite => valid_attributes}, valid_session
        response.should redirect_to(Supplysite.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved supplysite as @supplysite" do
        # Trigger the behavior that occurs when invalid params are submitted
        Supplysite.any_instance.stub(:save).and_return(false)
        post :create, {:supplysite => {}}, valid_session
        assigns(:supplysite).should be_a_new(Supplysite)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Supplysite.any_instance.stub(:save).and_return(false)
        post :create, {:supplysite => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested supplysite" do
        supplysite = Supplysite.create! valid_attributes
        # Assuming there are no other supplysites in the database, this
        # specifies that the Supplysite created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Supplysite.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => supplysite.to_param, :supplysite => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested supplysite as @supplysite" do
        supplysite = Supplysite.create! valid_attributes
        put :update, {:id => supplysite.to_param, :supplysite => valid_attributes}, valid_session
        assigns(:supplysite).should eq(supplysite)
      end

      it "redirects to the supplysite" do
        supplysite = Supplysite.create! valid_attributes
        put :update, {:id => supplysite.to_param, :supplysite => valid_attributes}, valid_session
        response.should redirect_to(supplysite)
      end
    end

    describe "with invalid params" do
      it "assigns the supplysite as @supplysite" do
        supplysite = Supplysite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Supplysite.any_instance.stub(:save).and_return(false)
        put :update, {:id => supplysite.to_param, :supplysite => {}}, valid_session
        assigns(:supplysite).should eq(supplysite)
      end

      it "re-renders the 'edit' template" do
        supplysite = Supplysite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Supplysite.any_instance.stub(:save).and_return(false)
        put :update, {:id => supplysite.to_param, :supplysite => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested supplysite" do
      supplysite = Supplysite.create! valid_attributes
      expect {
        delete :destroy, {:id => supplysite.to_param}, valid_session
      }.to change(Supplysite, :count).by(-1)
    end

    it "redirects to the supplysites list" do
      supplysite = Supplysite.create! valid_attributes
      delete :destroy, {:id => supplysite.to_param}, valid_session
      response.should redirect_to(supplysites_url)
    end
  end

end
