require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TranslinksController do

  # This should return the minimal set of attributes required to create a valid
  # Translink. As you add validations to Translink, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TranslinksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all translinks as @translinks" do
      translink = Translink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:translinks).should eq([translink])
    end
  end

  describe "GET show" do
    it "assigns the requested translink as @translink" do
      translink = Translink.create! valid_attributes
      get :show, {:id => translink.to_param}, valid_session
      assigns(:translink).should eq(translink)
    end
  end

  describe "GET new" do
    it "assigns a new translink as @translink" do
      get :new, {}, valid_session
      assigns(:translink).should be_a_new(Translink)
    end
  end

  describe "GET edit" do
    it "assigns the requested translink as @translink" do
      translink = Translink.create! valid_attributes
      get :edit, {:id => translink.to_param}, valid_session
      assigns(:translink).should eq(translink)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Translink" do
        expect {
          post :create, {:translink => valid_attributes}, valid_session
        }.to change(Translink, :count).by(1)
      end

      it "assigns a newly created translink as @translink" do
        post :create, {:translink => valid_attributes}, valid_session
        assigns(:translink).should be_a(Translink)
        assigns(:translink).should be_persisted
      end

      it "redirects to the created translink" do
        post :create, {:translink => valid_attributes}, valid_session
        response.should redirect_to(Translink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved translink as @translink" do
        # Trigger the behavior that occurs when invalid params are submitted
        Translink.any_instance.stub(:save).and_return(false)
        post :create, {:translink => {}}, valid_session
        assigns(:translink).should be_a_new(Translink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Translink.any_instance.stub(:save).and_return(false)
        post :create, {:translink => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested translink" do
        translink = Translink.create! valid_attributes
        # Assuming there are no other translinks in the database, this
        # specifies that the Translink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Translink.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => translink.to_param, :translink => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested translink as @translink" do
        translink = Translink.create! valid_attributes
        put :update, {:id => translink.to_param, :translink => valid_attributes}, valid_session
        assigns(:translink).should eq(translink)
      end

      it "redirects to the translink" do
        translink = Translink.create! valid_attributes
        put :update, {:id => translink.to_param, :translink => valid_attributes}, valid_session
        response.should redirect_to(translink)
      end
    end

    describe "with invalid params" do
      it "assigns the translink as @translink" do
        translink = Translink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Translink.any_instance.stub(:save).and_return(false)
        put :update, {:id => translink.to_param, :translink => {}}, valid_session
        assigns(:translink).should eq(translink)
      end

      it "re-renders the 'edit' template" do
        translink = Translink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Translink.any_instance.stub(:save).and_return(false)
        put :update, {:id => translink.to_param, :translink => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested translink" do
      translink = Translink.create! valid_attributes
      expect {
        delete :destroy, {:id => translink.to_param}, valid_session
      }.to change(Translink, :count).by(-1)
    end

    it "redirects to the translinks list" do
      translink = Translink.create! valid_attributes
      delete :destroy, {:id => translink.to_param}, valid_session
      response.should redirect_to(translinks_url)
    end
  end

end
